version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: cadastro-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    restart: always

  app-spring:
    image: educaetano0/cadastro-ninjas:0.0.1-RELEASE
    container_name: spring-app-ninjas
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}