CREATE TABLE tb_missoes (
    -- CORREÇÃO AQUI:
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(255),
                            dificuldade VARCHAR(255)
);

CREATE TABLE tb_cadastro (
    -- CORREÇÃO AQUI:
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(255),
                             idade INT NOT NULL,
                             email VARCHAR(255) UNIQUE,
                             img_url VARCHAR(255),
                             missoes_id BIGINT,
                             FOREIGN KEY (missoes_id) REFERENCES tb_missoes(id)
);